// <auto-generated />
using System;
using Cmms.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cmms.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260206175203_AddSundaySchedule")]
    partial class AddSundaySchedule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cmms.Domain.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<bool>("IsAct")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("Name");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("Cmms.Domain.AssetPart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAct")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PartId");

                    b.HasIndex("AssetId", "IsAct");

                    b.HasIndex("AssetId", "PartId")
                        .IsUnique();

                    b.ToTable("asset_parts", (string)null);
                });

            modelBuilder.Entity("Cmms.Domain.AssignmentRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AssignmentRoles");
                });

            modelBuilder.Entity("Cmms.Domain.CompanyBlackoutDay", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Date");

                    b.ToTable("CompanyBlackoutDays");
                });

            modelBuilder.Entity("Cmms.Domain.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("MinQty")
                        .HasColumnType("numeric");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QtyOnHand")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PartId");

                    b.ToTable("Inventory", (string)null);
                });

            modelBuilder.Entity("Cmms.Domain.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<bool>("IsAct")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Cmms.Domain.NationalHoliday", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Date");

                    b.ToTable("NationalHolidays");
                });

            modelBuilder.Entity("Cmms.Domain.Part", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<bool>("IsAct")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uom")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Parts", (string)null);
                });

            modelBuilder.Entity("Cmms.Domain.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("Cmms.Domain.PersonLeave", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PersonId", "StartDate", "EndDate");

                    b.ToTable("person_leaves", (string)null);
                });

            modelBuilder.Entity("Cmms.Domain.PersonWorkSchedule", b =>
                {
                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("MonFriEnd")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("MonFriStart")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("SatEnd")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("SatStart")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("SunEnd")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("SunStart")
                        .HasColumnType("interval");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PersonId");

                    b.ToTable("PersonWorkSchedules");
                });

            modelBuilder.Entity("Cmms.Domain.PmPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAct")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("NextDueAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.ToTable("PmPlans");
                });

            modelBuilder.Entity("Cmms.Domain.PmPlanAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PmPlanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("RoleId");

                    b.HasIndex("PmPlanId", "PersonId", "RoleId")
                        .IsUnique();

                    b.ToTable("PmPlanAssignments");
                });

            modelBuilder.Entity("Cmms.Domain.PmPlanItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PmPlanId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sort")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PmPlanId");

                    b.ToTable("PmPlanItems");
                });

            modelBuilder.Entity("Cmms.Domain.WorkOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedToPersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ExtraRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PmPlanId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("StopAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("AssignedToPersonId");

                    b.ToTable("WorkOrders");
                });

            modelBuilder.Entity("Cmms.Domain.WorkOrderAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("PlannedFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("PlannedTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("RoleId");

                    b.HasIndex("WorkOrderId", "PersonId");

                    b.HasIndex("WorkOrderId", "PersonId", "RoleId")
                        .IsUnique();

                    b.ToTable("WorkOrderAssignments");
                });

            modelBuilder.Entity("Cmms.Domain.WorkOrderPart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsUniversal")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QtyUsed")
                        .HasColumnType("numeric");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PartId");

                    b.HasIndex("WorkOrderId", "PartId");

                    b.ToTable("WorkOrderParts", (string)null);
                });

            modelBuilder.Entity("Cmms.Domain.Asset", b =>
                {
                    b.HasOne("Cmms.Domain.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Cmms.Domain.AssetPart", b =>
                {
                    b.HasOne("Cmms.Domain.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cmms.Domain.Part", "Part")
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("Cmms.Domain.InventoryItem", b =>
                {
                    b.HasOne("Cmms.Domain.Part", "Part")
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");
                });

            modelBuilder.Entity("Cmms.Domain.PersonLeave", b =>
                {
                    b.HasOne("Cmms.Domain.Person", "Person")
                        .WithMany("Leaves")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Cmms.Domain.PersonWorkSchedule", b =>
                {
                    b.HasOne("Cmms.Domain.Person", "Person")
                        .WithOne("WorkSchedule")
                        .HasForeignKey("Cmms.Domain.PersonWorkSchedule", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Cmms.Domain.PmPlan", b =>
                {
                    b.HasOne("Cmms.Domain.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Cmms.Domain.PmPlanAssignment", b =>
                {
                    b.HasOne("Cmms.Domain.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cmms.Domain.PmPlan", "PmPlan")
                        .WithMany("Assignments")
                        .HasForeignKey("PmPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cmms.Domain.AssignmentRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("PmPlan");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Cmms.Domain.PmPlanItem", b =>
                {
                    b.HasOne("Cmms.Domain.PmPlan", "PmPlan")
                        .WithMany("Items")
                        .HasForeignKey("PmPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PmPlan");
                });

            modelBuilder.Entity("Cmms.Domain.WorkOrder", b =>
                {
                    b.HasOne("Cmms.Domain.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Cmms.Domain.Person", "AssignedToPerson")
                        .WithMany()
                        .HasForeignKey("AssignedToPersonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Asset");

                    b.Navigation("AssignedToPerson");
                });

            modelBuilder.Entity("Cmms.Domain.WorkOrderAssignment", b =>
                {
                    b.HasOne("Cmms.Domain.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cmms.Domain.AssignmentRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cmms.Domain.WorkOrder", "WorkOrder")
                        .WithMany("Assignments")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Role");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("Cmms.Domain.WorkOrderPart", b =>
                {
                    b.HasOne("Cmms.Domain.Part", "Part")
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cmms.Domain.WorkOrder", "WorkOrder")
                        .WithMany()
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("Cmms.Domain.Person", b =>
                {
                    b.Navigation("Leaves");

                    b.Navigation("WorkSchedule");
                });

            modelBuilder.Entity("Cmms.Domain.PmPlan", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Cmms.Domain.WorkOrder", b =>
                {
                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
